/*
 * Nicole Tao
 * IdealWeight.java
 * This program calculates a person's ideal weight or height
 * April 3rd, 2018
 */

package IdealWeight;

/**
 *
 * @author nitao5001
 */
import java.text.DecimalFormat;
public class IdealWeight extends javax.swing.JFrame {

    /**
     * Creates new form IdealWeight
     */
    public IdealWeight() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelSystem = new javax.swing.JLabel();
        labelHeight = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        textSystem = new javax.swing.JTextField();
        textHeight = new javax.swing.JTextField();
        labelSystem2 = new javax.swing.JLabel();
        labelHeight2 = new javax.swing.JLabel();
        buttonCalc = new javax.swing.JButton();
        labelOutput = new javax.swing.JLabel();
        textWeightHeight = new javax.swing.JTextField();
        labelWeightHeight = new javax.swing.JLabel();
        labelWeightHeight2 = new javax.swing.JLabel();
        labelWeight = new javax.swing.JLabel();
        textWeight = new javax.swing.JTextField();
        labelWeight2 = new javax.swing.JLabel();
        labelOr = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        labelTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTitle.setText("Ideal Weight and Height Calculator");

        labelName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelName.setText("Name:");

        labelSystem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSystem.setText("System of Measure:");

        labelHeight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelHeight.setText("Height:");

        labelSystem2.setText("(M)etrric or (I)mperial");

        labelHeight2.setText("entre height (inches or metres) if calculating weight");

        buttonCalc.setText("Calculate");
        buttonCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalcActionPerformed(evt);
            }
        });

        labelOutput.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelOutput.setForeground(new java.awt.Color(102, 102, 102));
        labelOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelWeightHeight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelWeightHeight.setText("Trying to calculate:");

        labelWeightHeight2.setText("Ideal (W)eight or ideal (H)eight");

        labelWeight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelWeight.setText("Weight:");

        labelWeight2.setText("entre weight (lbs or kgs) if calculating height");

        labelOr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelOr.setText("OR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelWeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelWeight2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCalc))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelName)
                            .addComponent(labelSystem)
                            .addComponent(labelWeightHeight)
                            .addComponent(labelHeight)
                            .addComponent(labelSystem2)
                            .addComponent(labelWeightHeight2)
                            .addComponent(labelHeight2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textWeightHeight)
                                .addComponent(textName, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                .addComponent(textSystem))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelTitle)
                        .addGap(9, 9, 9)))
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(labelOr)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSystem)
                    .addComponent(textSystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSystem2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWeightHeight)
                    .addComponent(textWeightHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelWeightHeight2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHeight)
                    .addComponent(textHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHeight2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelOr)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(textWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelWeight)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelWeight2)
                .addGap(15, 15, 15)
                .addComponent(buttonCalc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalcActionPerformed
        String name, system, weightHeight;
        name = textName.getText();
        system = textSystem.getText();
        weightHeight = textWeightHeight.getText();
        
        double height, weight;
        
        //Import decimal format to be used in output message
        DecimalFormat ideal = new DecimalFormat ("###.00");
        
        //if and else if statements that evaluates what to calculate and display based on what user enters 
        if ("M".equals(system) && "W".equals(weightHeight)){
            height = Double.parseDouble(textHeight.getText());
            //Calculates user's ideal weight based on height entered using the metric system
            weight = height*height*25; 
            labelOutput.setText("" + name + "'s ideal weight is " + (ideal.format(weight)) + " kgs");
        }
        else if ("M".equals(system) && "H".equals(weightHeight)){
            weight = Double.parseDouble(textWeight.getText());
            //Calculates user's ideal height based on weight entered using the metric system
            height = Math.sqrt(weight/25);
            labelOutput.setText("" + name + "'s ideal height is " + (ideal.format(height)) + " metres");
        }
        
        else if ("I".equals(system) && "W".equals(weightHeight)){
            height = Double.parseDouble(textHeight.getText());
            //Calculates user's ideal weight based on height entered using the imperial system
            weight = height*height*25/703;
            labelOutput.setText("" + name + "'s ideal weight is " + (ideal.format(weight)) + " lbs");
            
        }
        else if ("I".equals(system) && "H".equals(weightHeight)){
            weight = Double.parseDouble(textWeight.getText());
            //Calculates user's ideal height based on weight entered using the imperial system
            height = Math.sqrt(weight*703/25);
            labelOutput.setText("" + name + "'s ideal height is " + (ideal.format(height)) + (" inches"));
        }
        //If user doesn't fill in text fields or entered a wrong value, a message will display
        else
        {
            labelOutput.setText("Please enter appropriate values and fill in necessary text fields.");
        }


    }//GEN-LAST:event_buttonCalcActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IdealWeight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IdealWeight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IdealWeight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IdealWeight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IdealWeight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalc;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelHeight;
    private javax.swing.JLabel labelHeight2;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelOr;
    private javax.swing.JLabel labelOutput;
    private javax.swing.JLabel labelSystem;
    private javax.swing.JLabel labelSystem2;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelWeight;
    private javax.swing.JLabel labelWeight2;
    private javax.swing.JLabel labelWeightHeight;
    private javax.swing.JLabel labelWeightHeight2;
    private javax.swing.JTextField textHeight;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textSystem;
    private javax.swing.JTextField textWeight;
    private javax.swing.JTextField textWeightHeight;
    // End of variables declaration//GEN-END:variables
}
